tempio/urls.py
from django.contrib import admin
from django.urls import include, path

from . import api, views

urlpatterns = [
    path("", views.index),
    path("upload/", views.upload),
    path("tag/<slug>/", views.index),
    path("admin/", admin.site.urls),
    path("<file_id>/", views.view),
    path("<file_id>/view/", views.download),
    path("<file_id>/download/", views.download, {"as_attachment": True}),
    path("api/", include([path("files/", api.FilesAPI.as_view()), path("files/<slug>/", api.FilesAPI.as_view())])),
]

tempio/models.py
import base64
import datetime
import os

from django.conf import settings
from django.contrib.auth import get_user_model
from django.db import models
from django.db.models import Count
from django.template.defaultfilters import filesizeformat
from django.utils import timezone
from django.utils.crypto import get_random_string
from django.utils.text import slugify


def random_key():
    for attempt in range(5):
        key = get_random_string(7)
        if not File.objects.filter(slug=key).exists():
            return key
    raise RuntimeError("Could not generate a unique slug")


class Tag(models.Model):
    slug = models.SlugField()

    @classmethod
    def cleanup(cls):
        cls.objects.annotate(count=Count("files")).filter(count=0).delete()

    def __str__(self):
        return self.slug

    def get_absolute_url(self):
        return "/tag/{}/".format(self.slug)

    def get_api_url(self):
        return "/api/files/{}/".format(self.slug)


class File(models.Model):
    slug = models.SlugField(unique=True, default=random_key)
    name = models.CharField(max_length=200, blank=True)
    content_type = models.CharField(max_length=250)
    content = models.BinaryField()
    thumbnail = models.BinaryField(null=True, blank=True)
    description = models.TextField(blank=True)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, related_name="files", on_delete=models.CASCADE)
    tags = models.ManyToManyField(Tag, blank=True, related_name="files")
    date_created = models.DateTimeField(default=timezone.now)
    date_modified = models.DateTimeField(auto_now=True)
    date_expires = models.DateTimeField(null=True, blank=True)
    width = models.IntegerField(null=True, blank=True)
    height = models.IntegerField(null=True, blank=True)
    public = models.BooleanField(default=True)

    @classmethod
    def cleanup(cls):
        cls.objects.filter(date_expires__lt=timezone.now()).delete()
        # Remove transient users periodically.
        User = get_user_model()
        cutoff = timezone.now() - datetime.timedelta(days=settings.TEMPIO_USER_EXPIRATION)
        User.objects.annotate(num_files=Count("files")).filter(date_joined__lt=cutoff, num_files=0).delete()

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return "/{}/".format(self.slug)

    def get_view_url(self):
        return "{}view/".format(self.get_absolute_url())

    def get_download_url(self):
        return "{}download/".format(self.get_absolute_url())

    @property
    def is_image(self):
        return self.content_type.startswith("image/")

    @property
    def is_text(self):
        return self.content_type.startswith("text/") or "sql" in self.content_type

    @property
    def extension(self):
        name, ext = os.path.splitext(self.name)
        return ext[1:]

    @property
    def template(self):
        if self.is_image:
            return "image.html"
        elif self.is_text:
            return "text.html"
        else:
            return "file.html"

    @property
    def tag_text(self):
        return " ".join(t.slug for t in self.tags.order_by("slug")) if self.pk else ""

    def text(self):
        return self.content.decode("utf-8", "replace") if not self.is_image else ""

    def thumbnail_data(self):
        return (
            "data:image/png;base64,{}".format(base64.b64encode(self.thumbnail).decode("ascii"))
            if self.thumbnail
            else ""
        )

    def properties(self):
        props = {
            "Created": self.date_created,
            "Expires": self.date_expires or "Never",
            "Size": filesizeformat(len(self.content)),
            "Type": self.content_type,
        }
        if self.width:
            props["Width"] = self.width
        if self.height:
            props["Height"] = self.height
            # import exifread
            # tags = exifread.process_file(io.BytesIO(self.content), details=False)
            #  print(tags)
        return props

    def update_tags(self, text):
        tags = []
        for tag in text.split():
            tags.append(Tag.objects.get_or_create(slug=slugify(tag))[0])
        self.tags.set(tags)
        delete_ids = []
        for t in Tag.objects.annotate(num_files=Count("files")):
            if t.num_files == 0:
                delete_ids.append(t.pk)
        Tag.objects.filter(pk__in=delete_ids).delete()

tempio/views.py
import datetime
import io

from django.conf import settings
from django.db.models import Count, Q
from django.http import FileResponse, HttpResponse, JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.utils import timezone
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST
from PIL import Image, UnidentifiedImageError

from .models import File, Tag


def index(request, slug=None):
    File.cleanup()
    Tag.cleanup()
    files = File.objects.defer("content").order_by("-date_modified")
    if not request.user.is_superuser:
        files = files.filter(Q(public=True) | Q(owner=request.user))
    if slug:
        files = files.filter(tags__slug=slug)
    tags = Tag.objects.filter(files__in=files).annotate(num_files=Count("files")).order_by("-num_files")
    return render(request, "index.html", {"files": files[:50], "tags": tags, "slug": slug})


@csrf_exempt
@require_POST
def upload(request):
    upload = request.FILES["file"]
    if upload.size > settings.TEMPIO_MAX_SIZE:
        return JsonResponse({"error": "File too large."})
    content = upload.read()
    thumbnail = None
    width = None
    height = None
    expires = timezone.now() + datetime.timedelta(days=settings.TEMPIO_DEFAULT_EXPIRATION)
    if upload.content_type.startswith("image/"):
        try:
            im = Image.open(io.BytesIO(content))
            thumb = io.BytesIO()
            width, height = im.size
            im.thumbnail((200, 200))  # TODO: make this configurable
            im.save(thumb, "PNG")
            thumbnail = thumb.getvalue()
        except UnidentifiedImageError:
            pass
    f = File.objects.create(
        name=upload.name,
        content_type=upload.content_type,
        content=content,
        thumbnail=thumbnail,
        owner=request.user,
        date_expires=expires,
        width=width,
        height=height,
    )
    return JsonResponse({"url": f.get_absolute_url()})


def view(request, file_id):
    default_expires = timezone.now() + datetime.timedelta(days=settings.TEMPIO_DEFAULT_EXPIRATION)
    if file_id == "new":
        f = File(name="untitled.txt", content_type="text/plain", owner=request.user, date_expires=default_expires)
    else:
        f = get_object_or_404(File, slug=file_id)
    editable = (f.owner == request.user) or request.user.is_superuser
    if request.method == "POST":
        if editable:
            if "delete" in request.POST:
                f.delete()
            else:
                f.name = request.POST.get("name", f.name)
                f.description = request.POST.get("description", f.description)
                f.public = request.POST.get("public") == "1"
                if "content" in request.POST:
                    f.content = request.POST["content"].encode("utf-8")
                try:
                    expires = datetime.datetime.strptime(request.POST["expires"], "%Y-%m-%d").date()
                    if expires > datetime.date.today():
                        f.date_expires = timezone.now().replace(year=expires.year, month=expires.month, day=expires.day)
                except ValueError:
                    pass
                f.save()
                f.update_tags(request.POST.get("tags", ""))
        return redirect("/")
    return render(request, "view.html", {"file": f, "editable": editable})


def download(request, file_id, as_attachment=False):
    f = get_object_or_404(File, slug=file_id)
    if as_attachment:
        return FileResponse(io.BytesIO(f.content), as_attachment=True, filename=f.name, content_type=f.content_type)
    else:
        return HttpResponse(f.content, content_type=f.content_type)

tempio/templates/base.html
{% load static %}
{% load i18n %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>{% block title %}{{ site_name }}{% endblock %}</title>
        <link rel="stylesheet" href="{% static 'tempio.css' %}" />
        {% block css %}{% endblock css %}
    </head>
    <body>
        <div id="header">
            <a href="/">/{{ site_name }}</a>{% block header %}{% endblock header %}
        </div>
        <form action="" method="post">
            {% csrf_token %}
            <div id="content">
                {% block content %}{% endblock content %}
            </div>
            <div id="sidebar">
                {% block sidebar %}{% endblock sidebar %}
            </div>
        </form>
        <div id="fade">{% trans "Drop to upload" %}</div>
        <script src="{% static 'jquery-3.3.1.min.js' %}"></script>
        {% block javascript %}{% endblock javascript %}
    </body>
</html>

tempio/templates/file.html
{% load static %}
<img src="{% static 'file.svg' %}" width="200" alt="Download" style="margin-top:100px;" />

tempio/templates/image.html
<img class="shadow" src="{{ file.get_view_url }}" />

tempio/templates/index.html
{% extends "base.html" %}

{% load i18n %}
{% load static %}

{% block javascript %}
    <script src="{% static 'tempio.js' %}"></script>
{% endblock %}

{% block header %}{% if slug %}/{{ slug }}{% endif %}
	<a class="download" href="/new/">
		<img src="{% static 'plus.svg' %}" width="25" alt="{% trans 'New Document' %}" />
	</a>
	<a class="download">
		<img src="{% static 'upload.svg' %}" width="25" alt="{% trans 'Upload' %}" />
		<input type="file" name="file" id="upload" />
	</a>
{% endblock header %}

{% block content %}
	{% for f in files %}
		<a class="file" href="{{ f.get_absolute_url }}">
			<div class="thumb">
				{% if f.is_image and f.thumbnail %}
					<div class="image-center"><img src="{{ f.thumbnail_data }}" /></div>
				{% else %}
					{% if f.is_text %}
						{{ f.text|linebreaksbr }}
					{% else %}
						<img src="{% static 'file.svg' %}" alt="{{ f.name }}" style="opacity: 0.5;" />
					{% endif %}
				{% endif %}
			</div>
			<div class="name">{{ f.name }}</div>
		</a>
	{% endfor %}
{% endblock content %}

{% block sidebar %}
	{% for t in tags %}
		<a class="tag{% if t.slug == slug %} active{% endif %}" href="{{ t.get_absolute_url }}"><span class="text">{{ t }}</span><span class="count">{{ t.num_files }}</span></a>
	{% endfor %}
{% endblock sidebar %}

tempio/templates/text.html
<textarea name="content" autofocus{% if not editable %} disabled{% endif %}>{{ file.text }}</textarea>

tempio/templates/view.html
{% extends "base.html" %}

{% load static %}
{% load i18n %}

{% block title %}{{ site_name }} / {{ file.name }}{% endblock %}

{% block header %}/{{ file.name }}{% if not file.public %} ({% trans "PRIVATE" %}){% endif %}{% if file.pk %}<a class="download" href="{{ file.get_download_url }}"><img src="{% static 'download.svg' %}" width="25" alt="{% trans 'Download' %}" /></a>{% endif %}{% endblock header %}

{% block content %}
    {% include file.template %}
{% endblock content %}

{% block sidebar %}
    <label class="heading" for="id_name">{% trans "Name" %}</label>
    <input type="text" id="id_name" name="name" value="{{ file.name }}"{% if not editable %} disabled{% endif %} />
    <label class="heading" for="id_tags">{% trans "Tags" %}</label>
    <input type="text" id="id_tags" name="tags" value="{{ file.tag_text }}"{% if not editable %} disabled{% endif %} />
    <label class="heading" for="id_expires">{% trans "Expires" %}</label>
    <input type="date" id="id_expires" placeholder="yyyy-mm-dd" name="expires" value="{{ file.date_expires.date.isoformat }}"{% if not editable %} disabled{% endif %} />
    <label class="heading" for="id_description">{% trans "Description" %}</label>
    <textarea id="id_description" name="description"{% if not editable %} disabled{% endif %}>{{ file.description }}</textarea>
    <label class="heading">{% trans "Options" %}</label>
    <div class="options">
        <label class="checkbox">
            <input type="checkbox" name="public" value="1"{% if file.public %} checked="checked"{% endif %}{% if not editable %} disabled{% endif %} />
            {% trans "This file is public" %}
        </label>
    </div>
    <label class="heading" for="id_properties">{% trans "Properties" %}</label>
    <table class="properties">
        {% for name, value in file.properties.items %}
            <tr>
                <td>{{ name }}</td>
                <td>{{ value }}</td>
            </tr>
        {% endfor %}
    </table>
    {% if editable %}
        <button type="submit" class="primary">{% if file.pk %}{% trans "Update" %}{% else %}{% trans "Save" %}{% endif %}</button>
        {% if file.pk %}
            <button type="submit" name="delete" class="delete">{% trans "Delete" %}</button>
        {% endif %}
    {% endif %}
{% endblock sidebar %}